In [1]:
import numpy as np

1. convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
List= [12.23, 13.32, 100, 36.32]
Numpy_Array = np.array(List)
print(Numpy_Array)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
three_by_three = np.reshape(np.arange(2,11),(3,3))
print(three_by_three)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Create a null vector of size 10 and update sixth value to 11.

In [4]:
zeros_arr = np.zeros(10)
zeros_arr[6] = 11
print(zeros_arr)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4.program to reverse an array

In [5]:
new_arr = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
rev_new_arr = np.flip(new_arr)
rev_new_arr

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

5.program to create a 2d array with 1 on the border and 0 inside.

In [6]:
ones_arr = np.ones(25)
new_ones_arr = ones_arr.reshape(5,5)
new_ones_arr[1:4,1:4]=0
print(new_ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6.program to add a border (filled with 0's) around an existing array.

In [7]:
new3x3 = np.pad(three_by_three,1,'constant',constant_values = 0)
print(three_by_three)
print()
print(new3x3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[ 0  0  0  0  0]
 [ 0  2  3  4  0]
 [ 0  5  6  7  0]
 [ 0  8  9 10  0]
 [ 0  0  0  0  0]]


7.program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [8]:
new_array = np.zeros((8,8))
new_array[::2,::2]=1
new_array[1::2,1::2]=1
new_array


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

8.program to convert a list and tuple into arrays.

In [18]:
my_List = [1, 2, 3, 4, 5, 6, 7, 8]
my_List = np.array(my_List)
print(my_List)

my_tuple = (1,2,3,4)
print(np.array(my_tuple))

[1 2 3 4 5 6 7 8]
[1 2 3 4]


9.Write a Python program to append values to the end of an array

In [22]:
new_array1 = np.array([10, 20, 30])
np.append(new_array1,(40,50,60,70,80,90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

10.Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [41]:
eqn = np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
real = np.array([])
imaginary = np.array([])

print(eqn.real)
print(eqn.imag)


[1.         0.70710678]
[0.         0.70710678]


11.Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [46]:
x = np.array([1,2,3,4,5,6,100])
print("Elements of an array: ", x.size)
print("Length of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements: ", x.nbytes)

Elements of an array:  7
Length of one array element in bytes:  4
Total bytes consumed by the elements:  28


12.Write a Python program to find common values between two arrays.

In [53]:
Array1= np.array([0, 10, 20, 40, 60])
Array2= np.array([10, 30, 40])

print(np.intersect1d(Array1,Array2))

[10 40]


13.Write a Python program to find the set difference of two arrays.

In [55]:
Array1= np.array([ 0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70, 90])

print(np.setdiff1d(Array1,Array2))

[ 0 20 60 80]


14.Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [56]:
Array1= np.array([ 0, 10, 20, 40, 60, 80])
Array2= np.array([10, 30, 40, 50, 70])

print(np.setxor1d(Array1,Array2))

[ 0 20 30 50 60 70 80]


15.Write a Python program compare two arrays using numpy.

In [58]:
a = np.array([1, 2])
b = np.array([4, 5])

print(np.greater(a, b))
print(np.greater_equal(a, b))
print(np.less(a, b))
print(np.less_equal(a, b))

[False False]
[False False]
[ True  True]
[ True  True]


16.Write a Python program to create a contiguous flattened array.

In [59]:
x = np.array([[10, 20, 30], [20, 40, 50]])
y = np.ravel(x)
print(y)

[10 20 30 20 40 50]


17.Write a Python program to change the data type of an array.

In [65]:
Array1= np.array([ 0, 10, 20, 40, 60, 80])
print(Array1.dtype)
Array2 = Array1.astype(float)
print(Array2.dtype)

int32
float64


18.Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [66]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19.Write a Python program to create an array which looks like below array.

In [68]:
x = np.tri(4, 3,-1)
print(x)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20.Write a Python program to concatenate two 2-dimensional arrays. Expected Output:

In [72]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
arr3 = np.concatenate((a, b), 1)
print(arr3)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21.Write a Python program to make an array immutable

In [75]:
zeros_arr = np.zeros(10)
zeros_arr.flags.writeable = False

# zeros_arr[0] = 1

22.Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [78]:
arr = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4]])
print(arr*3)

[[ 3  6  9 12]
 [15 18 21 24]
 [ 3  6  9 12]]


23.Write a Python program to convert a NumPy array into Python list structure.

In [86]:
arr = np.arange(10)
print(type(arr))
new_arr = arr.tolist()
print(type(new_arr))

<class 'numpy.ndarray'>
<class 'list'>


24.Write a Python program to convert a NumPy array into Python list structure.

In [89]:
arr = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,0.35399976, 0.99469633, 0.0694458, 0.54711478])
new = arr.tolist()
np.set_printoptions(precision=3)
print(arr)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25.Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [100]:
arr = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
np.set_printoptions(precision = 2, suppress = True)
print(arr)

[   0.      1.6  1200.      0.23]


26.Write a Python program to how to add an extra column to an numpy array.

In [112]:
arr = np.array([[ 10, 20, 30],[ 40, 50, 60]])
new = np.array([[100],[200]])

print(np.append(arr,new,axis=1))


[[ 10  20  30 100]
 [ 40  50  60 200]]


27.Write a Python program to remove specific elements in a numpy array.

In [116]:
arr = np.array([1,2,3,4,5,6,7,8,9])
new = np.delete(arr,[3,1,5])
new

array([1, 3, 5, 7, 8, 9])